let boton = document.getElementById('botonJugar')
let txt = document.getElementById('txt')

let card = document.getElementById('Card')
let card2 = document.getElementById('Card2')
let card3 = document.getElementById('Card3')
let card4 = document.getElementById('Card4')
let card5 = document.getElementById('Card5')
let card6 = document.getElementById('Card6')
let card7 = document.getElementById('Card7')
let card8 = document.getElementById('Card8')
let card9 = document.getElementById('Card9')
let card10 = document.getElementById('Card10')
let card11 = document.getElementById('Card11')
let card12 = document.getElementById('Card12')
let card13 = document.getElementById('Card13')
let card14 = document.getElementById('Card14')
let card15 = document.getElementById('Card15')
let card16 = document.getElementById('Card16')

let imagen = document.getElementById('imagen')
let imagen2 = document.getElementById('imagen2')
let imagen3 = document.getElementById('imagen3')
let imagen4 = document.getElementById('imagen4')
let imagen5 = document.getElementById('imagen5')
let imagen6 = document.getElementById('imagen6')
let imagen7 = document.getElementById('imagen7')
let imagen8 = document.getElementById('imagen8')
let imagen9 = document.getElementById('imagen9')
let imagen10 = document.getElementById('imagen10')
let imagen11 = document.getElementById('imagen11')
let imagen12 = document.getElementById('imagen12')
let imagen13 = document.getElementById('imagen13')
let imagen14 = document.getElementById('imagen14')
let imagen15 = document.getElementById('imagen15')
let imagen16 = document.getElementById('imagen16')

boton.addEventListener('click', botoncito)

function botoncito(){
    txt.innerHTML = "hola"
}

function ponerFondo(){
    alert("Hola")
    txt.innerHTML = "hola"
    // document.getElementById('imagen').setAttribute('src', " ")
    // imagen.classList.toggle("respaldo")
    // imagen2.classList.toggle('respaldo')
    // imagen3.classList.toggle("respaldo")
    // imagen4.classList.toggle('respaldo')
    // imagen5.classList.toggle("respaldo")
    // imagen6.classList.toggle('respaldo')
    // imagen7.classList.toggle("respaldo")
    // imagen8.classList.toggle('respaldo')
    // imagen9.classList.toggle("respaldo")
    // imagen10.classList.toggle('respaldo')
    // imagen11.classList.toggle("respaldo")
    // imagen12.classList.toggle('respaldo')
    // imagen13.classList.toggle("respaldo")
    // imagen14.classList.toggle('respaldo')
    // imagen15.classList.toggle("respaldo")
    // imagen16.classList.toggle('respaldo')
}

